pipeline {
    agent {label "master"}
    stages {
        stage('initial') { 
            steps {
              script{
                  echo "hello1"
              }
            }
        }
        stage('Build') { 
            steps {
              script{
                  echo "hello2"
                  checkpoint 'TEST'
              }
            }
        }
        stage('Post'){
            steps{
                script{
                    echo "hello3"
                }
            }
        }
    }
}
