pipeline {
    agent {label "master"}
    stages {
        stage('Build') { 
            steps {
              script{
                  echo "hello"
                  checkpoint 'TEST'
              }
            }
        }
        stage('Post'){
            steps{
                script{
                    echo "hello2"
                }
            }
        }
    }
}
