pipeline {
  parameters {
        string(name: 'myparam_one', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'myparam_two', defaultValue: '', description: 'Enter some information about the person')
    }
    agent any
    stages {
        stage('Example') {
            steps {
                echo "Hello new ${myparam_one}"

                echo "Biography: ${myparam_two}"
              
            }
        }
    }
}
